#define PROXY_NONE 0xFFFF
#define PROXIES_N 65536

#define PROXY_POINTS_MAX   255U
#define PROXY_POINTS_ZERO  127U

struct StaticProxy {
    u32 ip;
    u16 port;
    u16 protocol;
};

#define PROXIES_CHILDS_N    4
#define PROXIES_CHILDS_BITS 2
#define PROXIES_CHILDS_MASK 0b11ULL

#define PROXIES_FIRSTS_N 1024 //

// AO DAR UM FREE NO PROXY, SE ELE AINDA ESTIVER EM USO, APENAS O RETIRE DO HASH TABLE
// NO CONNECTION_CLOSE(), SE O REF COUNT DER 0, AÍ SIM TERMINAR, LIMPANDO OS POINTS DE TODAS AS CLASSES, E O COLOQUE NUMA LINKED LIST
struct Proxy {
    u32 ip;
    u16 port;
    u16 protocol;
    u16 childs[PROXIES_CHILDS_N];
}; // TODO: FIXME: FAZER POR SITE, LIMITADO A 32.000, E NUNCA SOBRESCREVER OS QUE TIVER < 0xFF/2
